### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by fangio10** [mlabs-haskell/cardano-open-oracle-protocol#71]
just noticed the link to the catalyst idea in the readme is broken, https://cardano.ideascale.com/c/idea/402572

**Comment by bladyjoker** [comment]
Hey @fangio10 thanks for reporting this, I don't know how I missed it sorry about the delay!

I tried the link in the README https://cardano.ideascale.com/c/idea/402572 and it seems like it works and it just redirects to the new link https://cardano.ideascale.com/c/idea/62613. 

Seems like that's ok, so I'll go ahead and close this. Thanks again!
